// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/AddressBookDTO.proto

// Protobuf Java Version: 3.25.0
package com.joango;

public interface AddressBookDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddressBookDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>repeated .PersonDTO people = 2;</code>
   */
  java.util.List<com.joango.PersonDTO> 
      getPeopleList();
  /**
   * <code>repeated .PersonDTO people = 2;</code>
   */
  com.joango.PersonDTO getPeople(int index);
  /**
   * <code>repeated .PersonDTO people = 2;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .PersonDTO people = 2;</code>
   */
  java.util.List<? extends com.joango.PersonDTOOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .PersonDTO people = 2;</code>
   */
  com.joango.PersonDTOOrBuilder getPeopleOrBuilder(
      int index);
}
