// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/PersonDTO.proto

// Protobuf Java Version: 3.25.0
package com.joango;

/**
 * Protobuf type {@code PersonDTO}
 */
public final class PersonDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PersonDTO)
    PersonDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PersonDTO.newBuilder() to construct.
  private PersonDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PersonDTO() {
    name_ = "";
    email_ = "";
    phones_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PersonDTO();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.joango.PersonDTOOuterClass.internal_static_PersonDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.joango.PersonDTOOuterClass.internal_static_PersonDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.joango.PersonDTO.class, com.joango.PersonDTO.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object email_ = "";
  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.joango.PhoneNumberDTO> phones_;
  /**
   * <code>repeated .PhoneNumberDTO phones = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.joango.PhoneNumberDTO> getPhonesList() {
    return phones_;
  }
  /**
   * <code>repeated .PhoneNumberDTO phones = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.joango.PhoneNumberDTOOrBuilder> 
      getPhonesOrBuilderList() {
    return phones_;
  }
  /**
   * <code>repeated .PhoneNumberDTO phones = 4;</code>
   */
  @java.lang.Override
  public int getPhonesCount() {
    return phones_.size();
  }
  /**
   * <code>repeated .PhoneNumberDTO phones = 4;</code>
   */
  @java.lang.Override
  public com.joango.PhoneNumberDTO getPhones(int index) {
    return phones_.get(index);
  }
  /**
   * <code>repeated .PhoneNumberDTO phones = 4;</code>
   */
  @java.lang.Override
  public com.joango.PhoneNumberDTOOrBuilder getPhonesOrBuilder(
      int index) {
    return phones_.get(index);
  }

  public static final int LAST_UPDATED_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp lastUpdated_;
  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   * @return Whether the lastUpdated field is set.
   */
  @java.lang.Override
  public boolean hasLastUpdated() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   * @return The lastUpdated.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getLastUpdated() {
    return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
  }
  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
    return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
    }
    for (int i = 0; i < phones_.size(); i++) {
      output.writeMessage(4, phones_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getLastUpdated());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
    }
    for (int i = 0; i < phones_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, phones_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getLastUpdated());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.joango.PersonDTO)) {
      return super.equals(obj);
    }
    com.joango.PersonDTO other = (com.joango.PersonDTO) obj;

    if (getId()
        != other.getId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!getPhonesList()
        .equals(other.getPhonesList())) return false;
    if (hasLastUpdated() != other.hasLastUpdated()) return false;
    if (hasLastUpdated()) {
      if (!getLastUpdated()
          .equals(other.getLastUpdated())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    if (getPhonesCount() > 0) {
      hash = (37 * hash) + PHONES_FIELD_NUMBER;
      hash = (53 * hash) + getPhonesList().hashCode();
    }
    if (hasLastUpdated()) {
      hash = (37 * hash) + LAST_UPDATED_FIELD_NUMBER;
      hash = (53 * hash) + getLastUpdated().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.joango.PersonDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.joango.PersonDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.joango.PersonDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.joango.PersonDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.joango.PersonDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.joango.PersonDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.joango.PersonDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.joango.PersonDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.joango.PersonDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.joango.PersonDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.joango.PersonDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.joango.PersonDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.joango.PersonDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PersonDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PersonDTO)
      com.joango.PersonDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.joango.PersonDTOOuterClass.internal_static_PersonDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.joango.PersonDTOOuterClass.internal_static_PersonDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.joango.PersonDTO.class, com.joango.PersonDTO.Builder.class);
    }

    // Construct using com.joango.PersonDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPhonesFieldBuilder();
        getLastUpdatedFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      name_ = "";
      email_ = "";
      if (phonesBuilder_ == null) {
        phones_ = java.util.Collections.emptyList();
      } else {
        phones_ = null;
        phonesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      lastUpdated_ = null;
      if (lastUpdatedBuilder_ != null) {
        lastUpdatedBuilder_.dispose();
        lastUpdatedBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.joango.PersonDTOOuterClass.internal_static_PersonDTO_descriptor;
    }

    @java.lang.Override
    public com.joango.PersonDTO getDefaultInstanceForType() {
      return com.joango.PersonDTO.getDefaultInstance();
    }

    @java.lang.Override
    public com.joango.PersonDTO build() {
      com.joango.PersonDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.joango.PersonDTO buildPartial() {
      com.joango.PersonDTO result = new com.joango.PersonDTO(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.joango.PersonDTO result) {
      if (phonesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          phones_ = java.util.Collections.unmodifiableList(phones_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.phones_ = phones_;
      } else {
        result.phones_ = phonesBuilder_.build();
      }
    }

    private void buildPartial0(com.joango.PersonDTO result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.email_ = email_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.lastUpdated_ = lastUpdatedBuilder_ == null
            ? lastUpdated_
            : lastUpdatedBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.joango.PersonDTO) {
        return mergeFrom((com.joango.PersonDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.joango.PersonDTO other) {
      if (other == com.joango.PersonDTO.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (phonesBuilder_ == null) {
        if (!other.phones_.isEmpty()) {
          if (phones_.isEmpty()) {
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePhonesIsMutable();
            phones_.addAll(other.phones_);
          }
          onChanged();
        }
      } else {
        if (!other.phones_.isEmpty()) {
          if (phonesBuilder_.isEmpty()) {
            phonesBuilder_.dispose();
            phonesBuilder_ = null;
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000008);
            phonesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPhonesFieldBuilder() : null;
          } else {
            phonesBuilder_.addAllMessages(other.phones_);
          }
        }
      }
      if (other.hasLastUpdated()) {
        mergeLastUpdated(other.getLastUpdated());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              email_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.joango.PhoneNumberDTO m =
                  input.readMessage(
                      com.joango.PhoneNumberDTO.parser(),
                      extensionRegistry);
              if (phonesBuilder_ == null) {
                ensurePhonesIsMutable();
                phones_.add(m);
              } else {
                phonesBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getLastUpdatedFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      email_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      email_ = getDefaultInstance().getEmail();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string email = 3;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      email_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<com.joango.PhoneNumberDTO> phones_ =
      java.util.Collections.emptyList();
    private void ensurePhonesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        phones_ = new java.util.ArrayList<com.joango.PhoneNumberDTO>(phones_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.joango.PhoneNumberDTO, com.joango.PhoneNumberDTO.Builder, com.joango.PhoneNumberDTOOrBuilder> phonesBuilder_;

    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public java.util.List<com.joango.PhoneNumberDTO> getPhonesList() {
      if (phonesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(phones_);
      } else {
        return phonesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public int getPhonesCount() {
      if (phonesBuilder_ == null) {
        return phones_.size();
      } else {
        return phonesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public com.joango.PhoneNumberDTO getPhones(int index) {
      if (phonesBuilder_ == null) {
        return phones_.get(index);
      } else {
        return phonesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public Builder setPhones(
        int index, com.joango.PhoneNumberDTO value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.set(index, value);
        onChanged();
      } else {
        phonesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public Builder setPhones(
        int index, com.joango.PhoneNumberDTO.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.set(index, builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public Builder addPhones(com.joango.PhoneNumberDTO value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
      } else {
        phonesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public Builder addPhones(
        int index, com.joango.PhoneNumberDTO value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.add(index, value);
        onChanged();
      } else {
        phonesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public Builder addPhones(
        com.joango.PhoneNumberDTO.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.add(builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public Builder addPhones(
        int index, com.joango.PhoneNumberDTO.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.add(index, builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public Builder addAllPhones(
        java.lang.Iterable<? extends com.joango.PhoneNumberDTO> values) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phones_);
        onChanged();
      } else {
        phonesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public Builder clearPhones() {
      if (phonesBuilder_ == null) {
        phones_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        phonesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public Builder removePhones(int index) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.remove(index);
        onChanged();
      } else {
        phonesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public com.joango.PhoneNumberDTO.Builder getPhonesBuilder(
        int index) {
      return getPhonesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public com.joango.PhoneNumberDTOOrBuilder getPhonesOrBuilder(
        int index) {
      if (phonesBuilder_ == null) {
        return phones_.get(index);  } else {
        return phonesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public java.util.List<? extends com.joango.PhoneNumberDTOOrBuilder> 
         getPhonesOrBuilderList() {
      if (phonesBuilder_ != null) {
        return phonesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(phones_);
      }
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public com.joango.PhoneNumberDTO.Builder addPhonesBuilder() {
      return getPhonesFieldBuilder().addBuilder(
          com.joango.PhoneNumberDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public com.joango.PhoneNumberDTO.Builder addPhonesBuilder(
        int index) {
      return getPhonesFieldBuilder().addBuilder(
          index, com.joango.PhoneNumberDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .PhoneNumberDTO phones = 4;</code>
     */
    public java.util.List<com.joango.PhoneNumberDTO.Builder> 
         getPhonesBuilderList() {
      return getPhonesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.joango.PhoneNumberDTO, com.joango.PhoneNumberDTO.Builder, com.joango.PhoneNumberDTOOrBuilder> 
        getPhonesFieldBuilder() {
      if (phonesBuilder_ == null) {
        phonesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.joango.PhoneNumberDTO, com.joango.PhoneNumberDTO.Builder, com.joango.PhoneNumberDTOOrBuilder>(
                phones_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        phones_ = null;
      }
      return phonesBuilder_;
    }

    private com.google.protobuf.Timestamp lastUpdated_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastUpdatedBuilder_;
    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     * @return Whether the lastUpdated field is set.
     */
    public boolean hasLastUpdated() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     * @return The lastUpdated.
     */
    public com.google.protobuf.Timestamp getLastUpdated() {
      if (lastUpdatedBuilder_ == null) {
        return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
      } else {
        return lastUpdatedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     */
    public Builder setLastUpdated(com.google.protobuf.Timestamp value) {
      if (lastUpdatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastUpdated_ = value;
      } else {
        lastUpdatedBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     */
    public Builder setLastUpdated(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = builderForValue.build();
      } else {
        lastUpdatedBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     */
    public Builder mergeLastUpdated(com.google.protobuf.Timestamp value) {
      if (lastUpdatedBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          lastUpdated_ != null &&
          lastUpdated_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getLastUpdatedBuilder().mergeFrom(value);
        } else {
          lastUpdated_ = value;
        }
      } else {
        lastUpdatedBuilder_.mergeFrom(value);
      }
      if (lastUpdated_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     */
    public Builder clearLastUpdated() {
      bitField0_ = (bitField0_ & ~0x00000010);
      lastUpdated_ = null;
      if (lastUpdatedBuilder_ != null) {
        lastUpdatedBuilder_.dispose();
        lastUpdatedBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getLastUpdatedBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getLastUpdatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
      if (lastUpdatedBuilder_ != null) {
        return lastUpdatedBuilder_.getMessageOrBuilder();
      } else {
        return lastUpdated_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getLastUpdatedFieldBuilder() {
      if (lastUpdatedBuilder_ == null) {
        lastUpdatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLastUpdated(),
                getParentForChildren(),
                isClean());
        lastUpdated_ = null;
      }
      return lastUpdatedBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PersonDTO)
  }

  // @@protoc_insertion_point(class_scope:PersonDTO)
  private static final com.joango.PersonDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.joango.PersonDTO();
  }

  public static com.joango.PersonDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PersonDTO>
      PARSER = new com.google.protobuf.AbstractParser<PersonDTO>() {
    @java.lang.Override
    public PersonDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PersonDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PersonDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.joango.PersonDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

