// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/PersonDTO.proto

// Protobuf Java Version: 3.25.0
package com.joango;

public interface PersonDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PersonDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .PhoneNumberDTO phones = 4;</code>
   */
  java.util.List<com.joango.PhoneNumberDTO> 
      getPhonesList();
  /**
   * <code>repeated .PhoneNumberDTO phones = 4;</code>
   */
  com.joango.PhoneNumberDTO getPhones(int index);
  /**
   * <code>repeated .PhoneNumberDTO phones = 4;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .PhoneNumberDTO phones = 4;</code>
   */
  java.util.List<? extends com.joango.PhoneNumberDTOOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <code>repeated .PhoneNumberDTO phones = 4;</code>
   */
  com.joango.PhoneNumberDTOOrBuilder getPhonesOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   * @return Whether the lastUpdated field is set.
   */
  boolean hasLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   * @return The lastUpdated.
   */
  com.google.protobuf.Timestamp getLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder();
}
