// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/PhoneNumberDTO.proto

// Protobuf Java Version: 3.25.0
package com.joango;

public interface PhoneNumberDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PhoneNumberDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string number = 1;</code>
   * @return The number.
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 1;</code>
   * @return The bytes for number.
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>.PhoneType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.PhoneType type = 2;</code>
   * @return The type.
   */
  com.joango.PhoneType getType();
}
