// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExternalService.proto

// Protobuf Java Version: 3.25.0
package com.joango.services;

/**
 * Protobuf type {@code com.joango.services.CreateAddressBookResponse}
 */
public final class CreateAddressBookResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.joango.services.CreateAddressBookResponse)
    CreateAddressBookResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateAddressBookResponse.newBuilder() to construct.
  private CreateAddressBookResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateAddressBookResponse() {
    code_ = 0;
    message_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateAddressBookResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.joango.services.ExternalService.internal_static_com_joango_services_CreateAddressBookResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.joango.services.ExternalService.internal_static_com_joango_services_CreateAddressBookResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.joango.services.CreateAddressBookResponse.class, com.joango.services.CreateAddressBookResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ADDRESSBOOK_FIELD_NUMBER = 1;
  private com.joango.AddressBookDTO addressBook_;
  /**
   * <code>.AddressBookDTO addressBook = 1;</code>
   * @return Whether the addressBook field is set.
   */
  @java.lang.Override
  public boolean hasAddressBook() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.AddressBookDTO addressBook = 1;</code>
   * @return The addressBook.
   */
  @java.lang.Override
  public com.joango.AddressBookDTO getAddressBook() {
    return addressBook_ == null ? com.joango.AddressBookDTO.getDefaultInstance() : addressBook_;
  }
  /**
   * <code>.AddressBookDTO addressBook = 1;</code>
   */
  @java.lang.Override
  public com.joango.AddressBookDTOOrBuilder getAddressBookOrBuilder() {
    return addressBook_ == null ? com.joango.AddressBookDTO.getDefaultInstance() : addressBook_;
  }

  public static final int CODE_FIELD_NUMBER = 2;
  private int code_ = 0;
  /**
   * <code>.ResponseCode code = 2;</code>
   * @return The enum numeric value on the wire for code.
   */
  @java.lang.Override public int getCodeValue() {
    return code_;
  }
  /**
   * <code>.ResponseCode code = 2;</code>
   * @return The code.
   */
  @java.lang.Override public com.joango.ResponseCode getCode() {
    com.joango.ResponseCode result = com.joango.ResponseCode.forNumber(code_);
    return result == null ? com.joango.ResponseCode.UNRECOGNIZED : result;
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getAddressBook());
    }
    if (code_ != com.joango.ResponseCode.UNKNOWN_RESPONSE_CODE.getNumber()) {
      output.writeEnum(2, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAddressBook());
    }
    if (code_ != com.joango.ResponseCode.UNKNOWN_RESPONSE_CODE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.joango.services.CreateAddressBookResponse)) {
      return super.equals(obj);
    }
    com.joango.services.CreateAddressBookResponse other = (com.joango.services.CreateAddressBookResponse) obj;

    if (hasAddressBook() != other.hasAddressBook()) return false;
    if (hasAddressBook()) {
      if (!getAddressBook()
          .equals(other.getAddressBook())) return false;
    }
    if (code_ != other.code_) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAddressBook()) {
      hash = (37 * hash) + ADDRESSBOOK_FIELD_NUMBER;
      hash = (53 * hash) + getAddressBook().hashCode();
    }
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + code_;
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.joango.services.CreateAddressBookResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.joango.services.CreateAddressBookResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.joango.services.CreateAddressBookResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.joango.services.CreateAddressBookResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.joango.services.CreateAddressBookResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.joango.services.CreateAddressBookResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.joango.services.CreateAddressBookResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.joango.services.CreateAddressBookResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.joango.services.CreateAddressBookResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.joango.services.CreateAddressBookResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.joango.services.CreateAddressBookResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.joango.services.CreateAddressBookResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.joango.services.CreateAddressBookResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.joango.services.CreateAddressBookResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.joango.services.CreateAddressBookResponse)
      com.joango.services.CreateAddressBookResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.joango.services.ExternalService.internal_static_com_joango_services_CreateAddressBookResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.joango.services.ExternalService.internal_static_com_joango_services_CreateAddressBookResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.joango.services.CreateAddressBookResponse.class, com.joango.services.CreateAddressBookResponse.Builder.class);
    }

    // Construct using com.joango.services.CreateAddressBookResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAddressBookFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      addressBook_ = null;
      if (addressBookBuilder_ != null) {
        addressBookBuilder_.dispose();
        addressBookBuilder_ = null;
      }
      code_ = 0;
      message_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.joango.services.ExternalService.internal_static_com_joango_services_CreateAddressBookResponse_descriptor;
    }

    @java.lang.Override
    public com.joango.services.CreateAddressBookResponse getDefaultInstanceForType() {
      return com.joango.services.CreateAddressBookResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.joango.services.CreateAddressBookResponse build() {
      com.joango.services.CreateAddressBookResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.joango.services.CreateAddressBookResponse buildPartial() {
      com.joango.services.CreateAddressBookResponse result = new com.joango.services.CreateAddressBookResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.joango.services.CreateAddressBookResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.addressBook_ = addressBookBuilder_ == null
            ? addressBook_
            : addressBookBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.code_ = code_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.message_ = message_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.joango.services.CreateAddressBookResponse) {
        return mergeFrom((com.joango.services.CreateAddressBookResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.joango.services.CreateAddressBookResponse other) {
      if (other == com.joango.services.CreateAddressBookResponse.getDefaultInstance()) return this;
      if (other.hasAddressBook()) {
        mergeAddressBook(other.getAddressBook());
      }
      if (other.code_ != 0) {
        setCodeValue(other.getCodeValue());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getAddressBookFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              code_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.joango.AddressBookDTO addressBook_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.joango.AddressBookDTO, com.joango.AddressBookDTO.Builder, com.joango.AddressBookDTOOrBuilder> addressBookBuilder_;
    /**
     * <code>.AddressBookDTO addressBook = 1;</code>
     * @return Whether the addressBook field is set.
     */
    public boolean hasAddressBook() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.AddressBookDTO addressBook = 1;</code>
     * @return The addressBook.
     */
    public com.joango.AddressBookDTO getAddressBook() {
      if (addressBookBuilder_ == null) {
        return addressBook_ == null ? com.joango.AddressBookDTO.getDefaultInstance() : addressBook_;
      } else {
        return addressBookBuilder_.getMessage();
      }
    }
    /**
     * <code>.AddressBookDTO addressBook = 1;</code>
     */
    public Builder setAddressBook(com.joango.AddressBookDTO value) {
      if (addressBookBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        addressBook_ = value;
      } else {
        addressBookBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.AddressBookDTO addressBook = 1;</code>
     */
    public Builder setAddressBook(
        com.joango.AddressBookDTO.Builder builderForValue) {
      if (addressBookBuilder_ == null) {
        addressBook_ = builderForValue.build();
      } else {
        addressBookBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.AddressBookDTO addressBook = 1;</code>
     */
    public Builder mergeAddressBook(com.joango.AddressBookDTO value) {
      if (addressBookBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          addressBook_ != null &&
          addressBook_ != com.joango.AddressBookDTO.getDefaultInstance()) {
          getAddressBookBuilder().mergeFrom(value);
        } else {
          addressBook_ = value;
        }
      } else {
        addressBookBuilder_.mergeFrom(value);
      }
      if (addressBook_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.AddressBookDTO addressBook = 1;</code>
     */
    public Builder clearAddressBook() {
      bitField0_ = (bitField0_ & ~0x00000001);
      addressBook_ = null;
      if (addressBookBuilder_ != null) {
        addressBookBuilder_.dispose();
        addressBookBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.AddressBookDTO addressBook = 1;</code>
     */
    public com.joango.AddressBookDTO.Builder getAddressBookBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getAddressBookFieldBuilder().getBuilder();
    }
    /**
     * <code>.AddressBookDTO addressBook = 1;</code>
     */
    public com.joango.AddressBookDTOOrBuilder getAddressBookOrBuilder() {
      if (addressBookBuilder_ != null) {
        return addressBookBuilder_.getMessageOrBuilder();
      } else {
        return addressBook_ == null ?
            com.joango.AddressBookDTO.getDefaultInstance() : addressBook_;
      }
    }
    /**
     * <code>.AddressBookDTO addressBook = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.joango.AddressBookDTO, com.joango.AddressBookDTO.Builder, com.joango.AddressBookDTOOrBuilder> 
        getAddressBookFieldBuilder() {
      if (addressBookBuilder_ == null) {
        addressBookBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.joango.AddressBookDTO, com.joango.AddressBookDTO.Builder, com.joango.AddressBookDTOOrBuilder>(
                getAddressBook(),
                getParentForChildren(),
                isClean());
        addressBook_ = null;
      }
      return addressBookBuilder_;
    }

    private int code_ = 0;
    /**
     * <code>.ResponseCode code = 2;</code>
     * @return The enum numeric value on the wire for code.
     */
    @java.lang.Override public int getCodeValue() {
      return code_;
    }
    /**
     * <code>.ResponseCode code = 2;</code>
     * @param value The enum numeric value on the wire for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeValue(int value) {
      code_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.ResponseCode code = 2;</code>
     * @return The code.
     */
    @java.lang.Override
    public com.joango.ResponseCode getCode() {
      com.joango.ResponseCode result = com.joango.ResponseCode.forNumber(code_);
      return result == null ? com.joango.ResponseCode.UNRECOGNIZED : result;
    }
    /**
     * <code>.ResponseCode code = 2;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(com.joango.ResponseCode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      code_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ResponseCode code = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      bitField0_ = (bitField0_ & ~0x00000002);
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 3;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.joango.services.CreateAddressBookResponse)
  }

  // @@protoc_insertion_point(class_scope:com.joango.services.CreateAddressBookResponse)
  private static final com.joango.services.CreateAddressBookResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.joango.services.CreateAddressBookResponse();
  }

  public static com.joango.services.CreateAddressBookResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateAddressBookResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateAddressBookResponse>() {
    @java.lang.Override
    public CreateAddressBookResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateAddressBookResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateAddressBookResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.joango.services.CreateAddressBookResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

