// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExternalService.proto

// Protobuf Java Version: 3.25.0
package com.joango.services;

public interface EntityIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.joango.services.EntityId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
