// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MainService.proto

// Protobuf Java Version: 3.25.0
package com.joango.services;

/**
 * Protobuf type {@code com.joango.services.ProcessAddressBookCommand}
 */
public final class ProcessAddressBookCommand extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.joango.services.ProcessAddressBookCommand)
    ProcessAddressBookCommandOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProcessAddressBookCommand.newBuilder() to construct.
  private ProcessAddressBookCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProcessAddressBookCommand() {
    id_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProcessAddressBookCommand();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.joango.services.MainService.internal_static_com_joango_services_ProcessAddressBookCommand_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.joango.services.MainService.internal_static_com_joango_services_ProcessAddressBookCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.joango.services.ProcessAddressBookCommand.class, com.joango.services.ProcessAddressBookCommand.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESSBOOK_FIELD_NUMBER = 2;
  private com.joango.AddressBookDTO addressBook_;
  /**
   * <code>.AddressBookDTO addressBook = 2;</code>
   * @return Whether the addressBook field is set.
   */
  @java.lang.Override
  public boolean hasAddressBook() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.AddressBookDTO addressBook = 2;</code>
   * @return The addressBook.
   */
  @java.lang.Override
  public com.joango.AddressBookDTO getAddressBook() {
    return addressBook_ == null ? com.joango.AddressBookDTO.getDefaultInstance() : addressBook_;
  }
  /**
   * <code>.AddressBookDTO addressBook = 2;</code>
   */
  @java.lang.Override
  public com.joango.AddressBookDTOOrBuilder getAddressBookOrBuilder() {
    return addressBook_ == null ? com.joango.AddressBookDTO.getDefaultInstance() : addressBook_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getAddressBook());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAddressBook());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.joango.services.ProcessAddressBookCommand)) {
      return super.equals(obj);
    }
    com.joango.services.ProcessAddressBookCommand other = (com.joango.services.ProcessAddressBookCommand) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasAddressBook() != other.hasAddressBook()) return false;
    if (hasAddressBook()) {
      if (!getAddressBook()
          .equals(other.getAddressBook())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasAddressBook()) {
      hash = (37 * hash) + ADDRESSBOOK_FIELD_NUMBER;
      hash = (53 * hash) + getAddressBook().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.joango.services.ProcessAddressBookCommand parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.joango.services.ProcessAddressBookCommand parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.joango.services.ProcessAddressBookCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.joango.services.ProcessAddressBookCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.joango.services.ProcessAddressBookCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.joango.services.ProcessAddressBookCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.joango.services.ProcessAddressBookCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.joango.services.ProcessAddressBookCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.joango.services.ProcessAddressBookCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.joango.services.ProcessAddressBookCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.joango.services.ProcessAddressBookCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.joango.services.ProcessAddressBookCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.joango.services.ProcessAddressBookCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.joango.services.ProcessAddressBookCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.joango.services.ProcessAddressBookCommand)
      com.joango.services.ProcessAddressBookCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.joango.services.MainService.internal_static_com_joango_services_ProcessAddressBookCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.joango.services.MainService.internal_static_com_joango_services_ProcessAddressBookCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.joango.services.ProcessAddressBookCommand.class, com.joango.services.ProcessAddressBookCommand.Builder.class);
    }

    // Construct using com.joango.services.ProcessAddressBookCommand.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAddressBookFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      addressBook_ = null;
      if (addressBookBuilder_ != null) {
        addressBookBuilder_.dispose();
        addressBookBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.joango.services.MainService.internal_static_com_joango_services_ProcessAddressBookCommand_descriptor;
    }

    @java.lang.Override
    public com.joango.services.ProcessAddressBookCommand getDefaultInstanceForType() {
      return com.joango.services.ProcessAddressBookCommand.getDefaultInstance();
    }

    @java.lang.Override
    public com.joango.services.ProcessAddressBookCommand build() {
      com.joango.services.ProcessAddressBookCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.joango.services.ProcessAddressBookCommand buildPartial() {
      com.joango.services.ProcessAddressBookCommand result = new com.joango.services.ProcessAddressBookCommand(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.joango.services.ProcessAddressBookCommand result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.addressBook_ = addressBookBuilder_ == null
            ? addressBook_
            : addressBookBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.joango.services.ProcessAddressBookCommand) {
        return mergeFrom((com.joango.services.ProcessAddressBookCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.joango.services.ProcessAddressBookCommand other) {
      if (other == com.joango.services.ProcessAddressBookCommand.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasAddressBook()) {
        mergeAddressBook(other.getAddressBook());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getAddressBookFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.joango.AddressBookDTO addressBook_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.joango.AddressBookDTO, com.joango.AddressBookDTO.Builder, com.joango.AddressBookDTOOrBuilder> addressBookBuilder_;
    /**
     * <code>.AddressBookDTO addressBook = 2;</code>
     * @return Whether the addressBook field is set.
     */
    public boolean hasAddressBook() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.AddressBookDTO addressBook = 2;</code>
     * @return The addressBook.
     */
    public com.joango.AddressBookDTO getAddressBook() {
      if (addressBookBuilder_ == null) {
        return addressBook_ == null ? com.joango.AddressBookDTO.getDefaultInstance() : addressBook_;
      } else {
        return addressBookBuilder_.getMessage();
      }
    }
    /**
     * <code>.AddressBookDTO addressBook = 2;</code>
     */
    public Builder setAddressBook(com.joango.AddressBookDTO value) {
      if (addressBookBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        addressBook_ = value;
      } else {
        addressBookBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.AddressBookDTO addressBook = 2;</code>
     */
    public Builder setAddressBook(
        com.joango.AddressBookDTO.Builder builderForValue) {
      if (addressBookBuilder_ == null) {
        addressBook_ = builderForValue.build();
      } else {
        addressBookBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.AddressBookDTO addressBook = 2;</code>
     */
    public Builder mergeAddressBook(com.joango.AddressBookDTO value) {
      if (addressBookBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          addressBook_ != null &&
          addressBook_ != com.joango.AddressBookDTO.getDefaultInstance()) {
          getAddressBookBuilder().mergeFrom(value);
        } else {
          addressBook_ = value;
        }
      } else {
        addressBookBuilder_.mergeFrom(value);
      }
      if (addressBook_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.AddressBookDTO addressBook = 2;</code>
     */
    public Builder clearAddressBook() {
      bitField0_ = (bitField0_ & ~0x00000002);
      addressBook_ = null;
      if (addressBookBuilder_ != null) {
        addressBookBuilder_.dispose();
        addressBookBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.AddressBookDTO addressBook = 2;</code>
     */
    public com.joango.AddressBookDTO.Builder getAddressBookBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getAddressBookFieldBuilder().getBuilder();
    }
    /**
     * <code>.AddressBookDTO addressBook = 2;</code>
     */
    public com.joango.AddressBookDTOOrBuilder getAddressBookOrBuilder() {
      if (addressBookBuilder_ != null) {
        return addressBookBuilder_.getMessageOrBuilder();
      } else {
        return addressBook_ == null ?
            com.joango.AddressBookDTO.getDefaultInstance() : addressBook_;
      }
    }
    /**
     * <code>.AddressBookDTO addressBook = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.joango.AddressBookDTO, com.joango.AddressBookDTO.Builder, com.joango.AddressBookDTOOrBuilder> 
        getAddressBookFieldBuilder() {
      if (addressBookBuilder_ == null) {
        addressBookBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.joango.AddressBookDTO, com.joango.AddressBookDTO.Builder, com.joango.AddressBookDTOOrBuilder>(
                getAddressBook(),
                getParentForChildren(),
                isClean());
        addressBook_ = null;
      }
      return addressBookBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.joango.services.ProcessAddressBookCommand)
  }

  // @@protoc_insertion_point(class_scope:com.joango.services.ProcessAddressBookCommand)
  private static final com.joango.services.ProcessAddressBookCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.joango.services.ProcessAddressBookCommand();
  }

  public static com.joango.services.ProcessAddressBookCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProcessAddressBookCommand>
      PARSER = new com.google.protobuf.AbstractParser<ProcessAddressBookCommand>() {
    @java.lang.Override
    public ProcessAddressBookCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProcessAddressBookCommand> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProcessAddressBookCommand> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.joango.services.ProcessAddressBookCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

