// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MainService.proto

// Protobuf Java Version: 3.25.0
package com.joango.services;

public interface ProcessAddressBookCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.joango.services.ProcessAddressBookCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.AddressBookDTO addressBook = 2;</code>
   * @return Whether the addressBook field is set.
   */
  boolean hasAddressBook();
  /**
   * <code>.AddressBookDTO addressBook = 2;</code>
   * @return The addressBook.
   */
  com.joango.AddressBookDTO getAddressBook();
  /**
   * <code>.AddressBookDTO addressBook = 2;</code>
   */
  com.joango.AddressBookDTOOrBuilder getAddressBookOrBuilder();
}
